In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv(r'D:\Python\Projects\used_bikes\Used_Bikes.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Python\\Projects\\used_bikes\\Used_Bikes.csv'

In [ ]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [3]:
df.duplicated()

NameError: name 'df' is not defined

In [4]:
df.isnull().sum()

NameError: name 'df' is not defined

In [215]:
df.drop_duplicates(inplace=True)

In [216]:
df['city'].unique()

array(['Ahmedabad', 'Delhi', 'Bangalore', 'Mumbai', 'Kalyan', 'Faridabad',
       'Mettur', 'Hyderabad', 'Kaithal', 'Gurgaon', 'Pune', 'Noida',
       'Nashik', 'Kochi', 'Allahabad', 'Samastipur', 'Nadiad', 'Lucknow',
       'Jaipur', 'Karnal', 'Gorakhpur', 'Vidisha', 'Hosur', 'Bagalkot',
       'Baripara', 'Agra', 'Dharwad', 'Vadodara', 'Jalandhar', 'Surat',
       'Chennai', 'Navi Mumbai', 'Gandhidham', 'Visakhapatnam',
       'Thrissur', 'Kolkata', 'Ernakulam', 'Barasat', 'Ghaziabad',
       'Bhubaneshwar', 'Amritsar', 'Bhopal', 'Hamirpur(hp)', 'Kottayam',
       'Arrah', 'Patiala', 'Ranga Reddy', 'Mandi', 'Ludhiana', 'Mandya',
       'Siliguri', 'Aurangabad', 'Kanpur', 'Bhilwara', 'Meerut', 'Rewari',
       'Ahmednagar', 'Wardha', 'Chandigarh', 'Ranchi', 'Panvel', 'Thane',
       'Jabalpur', 'Kota', 'Rohtak', 'Rajkot', 'Varanasi', '24 Pargana',
       'Banka', 'Nagpur', 'Banki', 'Pali', 'Chhatarpur', 'Katihar',
       'Mohali', 'Rudrapur', 'Coimbatore', 'Jajpur', 'Mysore', 'Adoni',

In [217]:
df['bike_name'].unique()

array(['TVS Star City Plus Dual Tone 110cc',
       'Royal Enfield Classic 350cc', 'Triumph Daytona 675R',
       'TVS Apache RTR 180cc', 'Yamaha FZ S V 2.0 150cc-Ltd. Edition',
       'Yamaha FZs 150cc', 'Honda CB Hornet 160R  ABS DLX',
       'Hero Splendor Plus Self Alloy 100cc',
       'Royal Enfield Thunderbird X 350cc',
       'Royal Enfield Classic Desert Storm 500cc',
       'Yamaha YZF-R15 2.0 150cc', 'Yamaha FZ25 250cc',
       'Bajaj Pulsar NS200', 'Bajaj Discover 100M', 'Bajaj Discover 125M',
       'Bajaj Pulsar NS200 ABS', 'Bajaj Pulsar RS200 ABS',
       'Suzuki Gixxer SF 150cc', 'Benelli 302R 300CC',
       'Hero Splendor iSmart Plus IBS 110cc',
       'Royal Enfield Classic Chrome 500cc', 'Yamaha FZ V 2.0 150cc',
       'Hero Super Splendor 125cc', 'Honda CBF Stunner 125cc',
       'Bajaj Pulsar 150cc', 'Honda X-Blade 160CC ABS',
       'Bajaj Avenger 220cc', 'KTM RC 390cc', 'Honda CB Unicorn 150cc',
       'KTM Duke 200cc', 'Honda CBR 150R 150cc',
       'Royal Enfiel

In [218]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [219]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [220]:
df.drop(['bike_name','city'],axis=1,inplace=True)

In [221]:
df

price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [222]:
dt={
    'First Owner':1,
    'Second Owner':2,
    'Third Owner':3,
    'Fourth Owner Or More':4
}
df['owner']=df['owner'].map(dt)

In [223]:
df['owner'].unique()

array([1, 2, 3, 4], dtype=int64)

In [224]:
df

price  kms_driven  owner  age  power            brand
0      35000.0     17654.0      1  3.0  110.0              TVS
1     119900.0     11000.0      1  4.0  350.0    Royal Enfield
2     600000.0       110.0      1  8.0  675.0          Triumph
3      65000.0     16329.0      1  4.0  180.0              TVS
4      80000.0     10000.0      1  3.0  150.0           Yamaha
...        ...         ...    ...  ...    ...              ...
9362   25000.0     48587.0      1  8.0  150.0             Hero
9369   35000.0     60000.0      1  9.0  220.0            Bajaj
9370  450000.0      3430.0      1  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0      1  4.0  400.0            Bajaj
9372   80000.0      7127.0      1  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [225]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement sklearn (from versions: none)
ERROR: No matching distribution found for sklearn


In [226]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [227]:
import sklearn as sk

In [228]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [229]:
encoder=LabelEncoder()

In [230]:
output=encoder.fit_transform(df['brand'])

In [231]:
# output.classes_

In [232]:
output

array([19, 17, 20, ...,  4,  1,  1])

In [233]:
df['brand']=output

In [234]:
output.shape

(7324,)

In [235]:
df.dtypes

price         float64
kms_driven    float64
owner           int64
age           float64
power         float64
brand           int32
dtype: object

In [236]:
x=df.drop('price',axis=1)
y=df[['price']]

In [237]:
x

kms_driven  owner  age  power  brand
0        17654.0      1  3.0  110.0     19
1        11000.0      1  4.0  350.0     17
2          110.0      1  8.0  675.0     20
3        16329.0      1  4.0  180.0     19
4        10000.0      1  3.0  150.0     21
...          ...    ...  ...    ...    ...
9362     48587.0      1  8.0  150.0      5
9369     60000.0      1  9.0  220.0      1
9370      3430.0      1  4.0  750.0      4
9371     21300.0      1  4.0  400.0      1
9372      7127.0      1  5.0  220.0      1

[7324 rows x 5 columns]

In [238]:
y

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [239]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0     19
1     119900.0     11000.0      1  4.0  350.0     17
2     600000.0       110.0      1  8.0  675.0     20
3      65000.0     16329.0      1  4.0  180.0     19
4      80000.0     10000.0      1  3.0  150.0     21
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      5
9369   35000.0     60000.0      1  9.0  220.0      1
9370  450000.0      3430.0      1  4.0  750.0      4
9371  139000.0     21300.0      1  4.0  400.0      1
9372   80000.0      7127.0      1  5.0  220.0      1

[7324 rows x 6 columns]

In [240]:
from sklearn.model_selection import train_test_split

In [241]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [242]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [243]:
x_train.head()
x_train.shape 

(5859, 5)

In [244]:
y_train.head()
y_train.shape

(5859, 1)

In [245]:
#from sklearn.linear_model import LinearRegression
from sklearn.ensemble import GradientBoostingRegressor

In [246]:
#lr =LinearRegression()
gb=GradientBoostingRegressor()

In [247]:
x_train.isnull()

kms_driven  owner    age  power  brand
5789       False  False  False  False  False
3451       False  False  False  False  False
735        False  False  False  False  False
7533       False  False  False  False  False
8461       False  False  False  False  False
...          ...    ...    ...    ...    ...
6522       False  False  False  False  False
6583       False  False  False  False  False
6856       False  False  False  False  False
1028       False  False  False  False  False
9250       False  False  False  False  False

[5859 rows x 5 columns]

In [248]:
#lr.fit(x_train,y_train)
gb.fit(x_train,y_train)

c:\Users\hp\anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:668: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?


GradientBoostingRegressor()

In [249]:
#print ("Testing Score:",lr.score(x_test,y_test))
print("Testing Score is:",gb.score(x_test,y_test))

Testing Score is: 0.8995082473955291


In [251]:
#lr.predict(x_test)
gb.predict(x_test)

array([ 99941.2040897 , 144231.52264847,  60970.51445021, ...,
        63161.10342403, 110946.69816322,  64010.45172761])

In [252]:
#pred=lr.predict(x_test)
pred=gb.predict(x_test)

In [253]:
pred

array([ 99941.2040897 , 144231.52264847,  60970.51445021, ...,
        63161.10342403, 110946.69816322,  64010.45172761])

In [254]:
x_test.shape

(1465, 5)

In [255]:
y_test['pred']=pred

In [256]:
y_test

price           pred
4909   88400.0   99941.204090
1942  102850.0  144231.522648
5763   67000.0   60970.514450
4800   30000.0   32997.551411
7614   20000.0   20601.623628
...        ...            ...
5653  395000.0  425461.752069
609   140000.0  153705.064510
4211   54500.0   63161.103424
6379  114000.0  110946.698163
647    36000.0   64010.451728

[1465 rows x 2 columns]

In [257]:
df

price  kms_driven  owner  age  power  brand
0      35000.0     17654.0      1  3.0  110.0     19
1     119900.0     11000.0      1  4.0  350.0     17
2     600000.0       110.0      1  8.0  675.0     20
3      65000.0     16329.0      1  4.0  180.0     19
4      80000.0     10000.0      1  3.0  150.0     21
...        ...         ...    ...  ...    ...    ...
9362   25000.0     48587.0      1  8.0  150.0      5
9369   35000.0     60000.0      1  9.0  220.0      1
9370  450000.0      3430.0      1  4.0  750.0      4
9371  139000.0     21300.0      1  4.0  400.0      1
9372   80000.0      7127.0      1  5.0  220.0      1

[7324 rows x 6 columns]

In [258]:
import joblib as jb

#loss function
MSE
MAE
RMSE
Huber loss

###MSE

In [259]:
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [260]:
y_test.drop('pred',axis=1,inplace=True)

In [261]:
print("mse:-",mean_squared_error(y_test,pred))

mse:- 1956445491.7755048


In [262]:
# pred ,y_test #actual #predicted

In [263]:
print("mae:-",mean_absolute_error(y_test,pred))

mae:- 15913.222565998294


RMSE

In [264]:
from sklearn.metrics import mean_squared_error
import math
import numpy as np

In [265]:
print("RMSE:-",math.sqrt(mean_squared_error(y_test,pred)))

RMSE:- 44231.724946869355


In [266]:
print('by using numpy:-',math.sqrt(mean_squared_error(y_test,pred)))

by using numpy:- 44231.724946869355


In [267]:
y_test

price
4909   88400.0
1942  102850.0
5763   67000.0
4800   30000.0
7614   20000.0
...        ...
5653  395000.0
609   140000.0
4211   54500.0
6379  114000.0
647    36000.0

[1465 rows x 1 columns]

Huber Loss

#Model Evaluation
confusion matrix
accuracy
precision
Recall
F1 Score

In [268]:
from sklearn.metrics import confusion_matrix,f1_score,precision_score,recall_score

In [269]:
pred=(pred>0.5).astype(int).ravel()

In [270]:
confusion_matrix(y_test,pred)

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [271]:
#print("precision:-",precision_score(y_test,pred))
#print("precision score:-",precision_score(y_test,pred))
#print("recall score",recall_score(y_test,pred))
#print("F1 score:",f1_score(y_test,pred))

In [272]:
import  matplotlib.pyplot as plt
import seaborn as sns

In [273]:
cm=confusion_matrix(y_test,pred)

In [274]:
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
#sns.heatmap(cm,annot=True,cmap='Blues',fmt='d')
#plt.title('confusion matrix')


In [2]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

In [3]:
obj=RandomForestClassifier()

In [4]:
obj=RandomForestRegressor()

In [5]:
obj.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': 1.0,
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [19]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [10]:
import xgboost as xgb

In [11]:
from sklearn.datasets import load_breast_cancer

In [12]:
x,y=load_breast_cancer(return_X_y=True)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [16]:
model_xg=xgb.XGBClassifier()

In [17]:
model_xg.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)