In [1]:
import numpy as np 

In [4]:
lst = [1,2,3,4,5]

In [5]:
type(lst)

list

In [7]:
arr = np.array(lst)

In [8]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [18]:
a = list(range(1,5))


In [19]:
a

[1, 2, 3, 4]

In [ ]:
arr = np.arange(1,10)
type(arr)

numpy.ndarray

In [24]:
arr = np.zeros((2,5)) 
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
arr = np.ones((2,3))

In [26]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr = np.ones((10))
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
arr = np.arange(10,32)

In [32]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [37]:
arr = np.random.randint(1,5,9)
arr

array([3, 4, 4, 2, 1, 1, 2, 2, 4])

In [39]:
arr = np.random.randint(1,5,(3,3))
arr

array([[2, 3, 3],
       [3, 4, 2],
       [4, 3, 3]])

In [41]:
list_2d = [[1,2,3],[4,5,6]]

In [42]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [43]:
arr = np.array(list_2d)

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
x = list(range(1,10))
y = list(range(11,20))


In [61]:
arr1 = np.array(x)
arr2 = np.array(y)

In [62]:
z = arr1*arr2

In [63]:
z

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])