In [1]:
import numpy as np 

In [2]:
lst = [1,2,3,4,5]

In [3]:
type(lst)

list

In [4]:
arr = np.array(lst)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
a = list(range(1,5))


In [8]:
a

[1, 2, 3, 4]

In [9]:
arr = np.arange(1,10)
type(arr)

numpy.ndarray

In [10]:
arr = np.zeros((2,5)) 
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
arr = np.ones((2,3))

In [12]:
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr = np.ones((10))
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
arr = np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [15]:
arr = np.arange(10,32)

In [16]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [17]:
arr = np.random.randint(1,5,9)
arr

array([1, 4, 3, 3, 4, 1, 3, 2, 2], dtype=int32)

In [18]:
arr = np.random.randint(1,5,(3,3))
arr

array([[2, 2, 4],
       [1, 4, 1],
       [4, 1, 1]], dtype=int32)

In [19]:
list_2d = [[1,2,3],[4,5,6]]

In [20]:
list_2d

[[1, 2, 3], [4, 5, 6]]

In [21]:
arr = np.array(list_2d)

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
x = list(range(1,10))
y = list(range(11,20))


In [25]:
arr1 = np.array(x)
arr2 = np.array(y)

In [26]:
z = arr1*arr2

In [27]:
z

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])